server.port=8080

# PostgreSQL Configuration
# Swap these with your Supabase Transaction URL and password when ready
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.xmrohvlpqsuzglxnqiff
spring.datasource.password=wKZNKz5SkFsphxP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Security Configuration
server.error.include-message=always
